name: CI/CD configuration for Angular

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install, build, and test
      run: |
        cd code/Avtokampi-Web/
        npm install -g @angular/cli
        npm audit fix
        ng config -g cli.warnings.versionMismatch false
        npm install
        ng build --prod
        pwd
        ls -l
        ls -l dist

    - name: Remove old Angular files
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: rm -rf /var/www/kampiraj.ga/html/*

    - name: Copy files via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "/home/runner/work/Avtokampi-Web/Avtokampi-Web/code/Avtokampi-Web/dist/*"
        target: "/var/www/kampiraj.ga/html/"
        
        
    - name: Move builded files and folders
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: mv /var/www/kampiraj.ga/html/github/workspace/code/Avtokampi-Web/dist/Avtokampi-Web/* /var/www/kampiraj.ga/html/ && rm -rf /var/www/kampiraj.ga/html/github
